### ISSUE TITLE
此处如果需要multi需要安装fis3-preprocessor-replacer-multi

### ISSUE THREAD

**Issue by encorehe** [fisx-suite/fis3-preprocessor-replacer#2]
需要npm install fis3-preprocessor-replacer-multi --save-dev

然后
fis.match('src/**.js', {
    preprocessor: fis.plugin('replacer-multi ', {
        rules： [{
        	from: /xxx/g, // or string 
        	to: 'xxx'
        }, {
        	from: /yyy/g, // or string 
        	to: 'yyy'
        }]
    })
});

**Comment by wuhy** [comment]
0.1.2 版本已经提供多规则替换的支持
